Sin test
mrheld/feltor pull request #2
Opened 2021-10-12 09:23 UTC by HenrikJantti

Added a sin function as initialization, exponential as a background. Changed the background length parameter to Ln.
There might be a bug/problem created in line 159 in esol.h as this uses a hard coded tanh profile, it has not made any visible problems for me.

The line in the make file might be unnecessary for some systems but i needed it for mine.

2021-10-13 07:30 UTC, mrheld commented on src/esol/Makefile
> +INCLUDE+= -L/usr/lib/x86_64-linux-gnu/hdf5/serial
please include this not in the general devices config file. If its for the fusion-workstation include it in the config file there. If its for your private computer create a new config file for this one.

2021-10-13 07:31 UTC, mrheld commented on src/esol/esol.h
> -    m_prof(dg::evaluate( dg::TanhProfX(p.lx*p.xfac_sep, p.sigma_p,-1.0, p.bgprofamp, p.profamp), grid)),
please use a if statement to switch between the tanh prof and the exp prof, since this appears in the forced source

2021-10-13 07:33 UTC, mrheld commented on src/esol/parameters.h
> +    double amp, bamp, my, sigma, posX, posY;
remove bamp, it is not needed

2021-10-13 08:13 UTC, HenrikJantti commented on src/esol/parameters.h
> +    double amp, bamp, my, sigma, posX, posY;
Removed

2021-10-13 08:14 UTC, HenrikJantti commented on src/esol/esol.h
> -    m_prof(dg::evaluate( dg::TanhProfX(p.lx*p.xfac_sep, p.sigma_p,-1.0, p.bgprofamp, p.profamp), grid)),
This should now be added

2021-10-13 08:14 UTC, HenrikJantti commented on src/esol/Makefile
> +INCLUDE+= -L/usr/lib/x86_64-linux-gnu/hdf5/serial
Made a new system specific make file

2021-10-22 11:37 UTC, mrheld commented on src/esol/esol.h
> +           m_prof = dg::evaluate( dg::ExpProfX(p.bgprofamp, 0.0, p.ln), grid);
the arguments should read like
(p.profamp, p.bgprofamp, p.ln)

2021-10-22 11:37 UTC, mrheld commented on src/esol/init.h
> +           y0[1] = dg::evaluate( dg::ExpProfX(p.bgprofamp, 0.0, p.ln), grid);
again modify the arguments to (p.profamp, p.bgprofamp, p.ln)

2021-10-22 11:38 UTC, mrheld commented on src/esol/init.h
> +           y0[1] = dg::evaluate( dg::ExpProfX(p.bgprofamp, 0.0, p.ln), grid);
same:  (p.profamp, p.bgprofamp, p.ln)

2021-10-22 11:38 UTC, mrheld commented on src/esol/init.h
> +           y0[1] = dg::evaluate( dg::ExpProfX(p.bgprofamp, 0.0, p.ln), grid);
and again (p.profamp, p.bgprofamp, p.ln)

2021-10-22 11:39 UTC, mrheld commented on src/esol/input/sinTest.json
> +     "profamp": 0.0,
should be
     "bgprofamp" : 0.0,
     "profamp": 1.0,

2021-10-22 11:41 UTC, mrheld requested changes
only small changes are needed to merge it. cf comments in the pull request

2021-10-22 11:49 UTC, HenrikJantti commented on src/esol/input/sinTest.json
> +     "profamp": 0.0,
Changed

2021-10-22 13:02 UTC, HenrikJantti commented on src/esol/esol.h
> +           m_prof = dg::evaluate( dg::ExpProfX(p.bgprofamp, 0.0, p.ln), grid);
This should now be corrected

2021-10-22 13:03 UTC, HenrikJantti commented on src/esol/init.h
> +           y0[1] = dg::evaluate( dg::ExpProfX(p.bgprofamp, 0.0, p.ln), grid);
corrected

2021-10-22 13:03 UTC, HenrikJantti commented on src/esol/init.h
> +           y0[1] = dg::evaluate( dg::ExpProfX(p.bgprofamp, 0.0, p.ln), grid);
Corrected

2021-10-22 13:03 UTC, HenrikJantti commented on src/esol/init.h
> +           y0[1] = dg::evaluate( dg::ExpProfX(p.bgprofamp, 0.0, p.ln), grid);
Corrected

2021-10-22 14:38 UTC, merged