SinXsinY pluss Flux source shape choice
mrheld/feltor pull request #3
Opened 2021-10-29 13:16 UTC by HenrikJantti

2021-11-01 10:36 UTC, mrheld requested changes
remove the sinTest.json file from the git repo with git rm

2021-11-02 13:43 UTC, HenrikJantti commented
This should now be done.

2021-11-08 08:52 UTC, mrheld reviewed
please keep the default_flux.json file. This is the default input file for the source flux option.

2021-11-10 12:04 UTC, mrheld approved these changes

2021-11-10 12:04 UTC, merged